створено календар
Boroda-Dmitro/js_ny-times-news pull request #5
Opened 2023-03-26 14:53 UTC by ValentynaSira1

2023-03-26 18:49 UTC, pelmenvasili commented on src/js/calendar.js
> +const calendarForm = document.querySelector('calendar-form');
пропущено точку, має бути ('.calendar-form')

2023-03-26 18:50 UTC, pelmenvasili commented on src/js/calendar.js
> +function calendarEl(e) {
(e) зазначається, але у функції не використовується.

2023-03-26 18:52 UTC, pelmenvasili commented on src/js/calendar.js
> +      throw new Error(err);
(err) не визначений

2023-03-26 18:57 UTC, pelmenvasili commented on src/partials/calendar.html
> +        <svg class="calendar__button-down dark-theme-btn" width="14" height="14">
немає батьківського блоку по бем, можна перейменувати в calendar-form__button-down, наприклад.

2023-03-26 19:00 UTC, pelmenvasili commented on src/partials/calendar.html
> +              <span id="prev-years" class="icon-symbols__years">
так само немає бб, можна назвати switches-years__icon

2023-03-26 19:01 UTC, pelmenvasili commented on src/partials/calendar.html
> +                <svg width="16" height="12" class="calendar__icon-right">
calendar-switcher__icon-right

2023-03-26 19:02 UTC, pelmenvasili commented on src/partials/calendar.html
> +              <span id="next-years" class="icon-symbols__years">
switches-years__icon

2023-03-26 19:04 UTC, pelmenvasili commented on src/partials/calendar.html
> +                <svg width="16" height="12" class="calendar__icon-left">
calendar-switcher__icon-left

2023-03-26 19:05 UTC, pelmenvasili commented on src/partials/calendar.html
> +                <svg width="16" height="17" class="calendar__icon-right">
calendar-icons__right

2023-03-26 19:05 UTC, pelmenvasili commented on src/partials/calendar.html
> +                <svg width="16" height="17" class="calendar__icon-left">
calendar-icons__left

2023-03-26 19:06 UTC, pelmenvasili commented on src/partials/calendar.html
> +          <div class="calendar">
calendar-weeks

2023-03-26 19:11 UTC, pelmenvasili commented on src/sass/components/home-page/_calendar.scss
> +    color: var(--color-brand);
тут має бути fill, а не color, щоб були значки синього кольору, як га макеті

2023-03-26 19:15 UTC, pelmenvasili commented on src/partials/calendar.html
> +        <svg class="form-container__icon-calendar" width="14" height="14">
width і height по 20 повинні бути, а ще при наведенні не видно іконку календарика, коли фон синій.

2023-03-26 19:17 UTC, pelmenvasili commented on src/partials/calendar.html
> +          placeholder="Виберіть дату..."
по макету одразу повинна бути поточна дата на інпуті, як я розумію, а не "виберіть дату", тому потрібно буде додати ще такий функціонал.

2023-03-26 19:18 UTC, pelmenvasili commented on src/sass/components/home-page/_calendar.scss
> +    z-index: 2;
чомусь через календар просвічуються новини, тому мені здається, що z-index десь не спрацював.

2023-03-26 19:21 UTC, pelmenvasili requested changes
потрібно трішки внести зміни.

2023-03-27 07:34 UTC, ValentynaSira1 commented on src/js/calendar.js
> +const calendarForm = document.querySelector('calendar-form');
виправила

2023-03-27 07:52 UTC, ValentynaSira1 commented on src/partials/calendar.html
> +                <svg width="16" height="12" class="calendar__icon-right">
✔

2023-03-27 07:54 UTC, ValentynaSira1 commented on src/partials/calendar.html
> +              <span id="next-years" class="icon-symbols__years">
✔

2023-03-27 07:54 UTC, ValentynaSira1 commented on src/partials/calendar.html
> +                <svg width="16" height="12" class="calendar__icon-left">
✔

2023-03-27 08:00 UTC, ValentynaSira1 commented on src/partials/calendar.html
> +                <svg width="16" height="17" class="calendar__icon-right">
✔

2023-03-27 08:04 UTC, ValentynaSira1 commented on src/sass/components/home-page/_calendar.scss
> +    color: var(--color-brand);
✔

2023-03-27 08:06 UTC, ValentynaSira1 commented on src/partials/calendar.html
> +          placeholder="Виберіть дату..."
в ТЗ написано, що повинен бути плейсхолдер "Виберіть дату..."

2023-03-27 17:10 UTC, closed without merging